name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.0.0
      with:
        version: 3.1.100
     
    - name: dotnet build
      run: dotnet build FeatherHttp.sln -c Release

    - name: assign version env
      run: | 
        $featherVersion = Get-ChildItem .\src\FeatherHttp\bin\Release\netcoreapp3.1\FeatherHttp.dll | Select-Object -ExpandProperty VersionInfo | Select-Object ProductVersion | Select-Object -ExpandProperty ProductVersion
        echo $featherVersion > NUGET_VERSION
     
    - name: dotnet test
      run: dotnet test FeatherHttp.sln -c Release --no-build

    - name: dotnet pack
      run: dotnet pack FeatherHttp.sln -c Release --no-build --include-source --include-symbols

    - name: setup nuget
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: NuGet/setup-nuget@v1.0.2
      with:
        nuget-version: latest

    - name: Set API key
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: nuget setapikey ${{ secrets.FEEDZ_TOKEN }} -Config nuget.config -Source https://f.feedz.io/davidfowl/featherhttp/nuget/index.json

    - name: Set symbols API key
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: nuget setapikey ${{ secrets.FEEDZ_TOKEN }} -Config nuget.config -Source https://f.feedz.io/davidfowl/featherhttp/symbols

    - name: push packages
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: dotnet nuget push **/*.nupkg -s https://f.feedz.io/davidfowl/featherhttp/nuget/index.json -ss https://f.feedz.io/davidfowl/featherhttp/symbols --skip-duplicate
    
    - uses: actions/checkout@master
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        ref: ${{ github.ref }} 

    - name: test if feather-version
      run: echo $(cat NUGET_VERSION)
    
    - name: install nbgv
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: dotnet tool install --tool-path . nbgv;

    - name: nuget version update
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: | 
        powershell ./update-nuget-references.ps1
        git status        

    - name: Commit files
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"        
        git commit -m "Updated Nuget Version" -a

    - name: Push changes
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: test build template
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: dotnet build ./template/content/featherhttp-template.csproj


  

      

